### ISSUE TITLE
NullPointerException in readAllDocuments()

### ISSUE THREAD

**Issue by jchamberlain** [freedev/solr-import-export-json#33]
When I run the first example,
```./run.sh -s http://localhost:8983/solr/collection -a export -o /tmp/collection.json```

I get the following error:
```15:07:40.324 [main] INFO  i.d.s.i.c.ConfigFactory - Current configuration CommandLineConfig{actionType=EXPORT, solrUrl='http://localhost:8983/solr/collection', fileName='/tmp/collection.json', deleteAll=false, disableCursors=false, skipFieldSet=[], includeFieldSet=[], filterQuery='null', uniqueKey='null', dryRun=false, skipCount=0, commitAfter=null, blockSize=5000, dateTimeFormat='YYYY-MM-dd'T'HH:mm:sss'Z'', user='null', password='**********'}
15:07:40.329 [main] INFO  i.d.s.i.App - Found config: CommandLineConfig{actionType=EXPORT, solrUrl='http://localhost:8983/solr/collection', fileName='/tmp/collection.json', deleteAll=false, disableCursors=false, skipFieldSet=[], includeFieldSet=[], filterQuery='null', uniqueKey='null', dryRun=false, skipCount=0, commitAfter=null, blockSize=5000, dateTimeFormat='YYYY-MM-dd'T'HH:mm:sss'Z'', user='null', password='**********'}
15:07:40.348 [main] WARN  i.d.s.i.App - unable to find valid uniqueKey defaulting to "id".
Exception in thread "main" java.lang.NullPointerException
	at it.damore.solr.importexport.App.readAllDocuments(App.java:324)
	at it.damore.solr.importexport.App.main(App.java:116)
```

I'm using Java 8 and running the master branch of this project. (To be clear, I've replaced "collection" with a real collection name when I get this error.)

Note that the following command succeeds (no NPE):
```./run.sh -s http://localhost:8983/solr/collection -a export -o /tmp/collection.json --user= --password=```

**Comment by freedev** [comment]
Hi @jchamberlain thanks for pointing out the problem, now it is fixed.

**Comment by freedev** [comment]
Recently I've added credential handling for basic authentication, but I forgot to check when there are no credential at all, ouch!
